name: "Code Analysis"

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4.1.7

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: 3.24.0
          channel: stable
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: 📦 Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          flutter pub global activate coverage

      - name: 🦄 Generate Code
        run: |
          dart run build_runner build -d

      - name: Install DCM
        uses: CQLabs/setup-dcm@v1.1.1
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: ✨ Check Formatting
        run: find lib test -name "*.dart" ! -name "*.*.dart" -print0 | xargs -0 dart format --set-exit-if-changed --line-length 100 -o none

      - name: 🕵️ Analyze
        run: flutter analyze .

      - name: 🧪 Run Tests
        run: flutter test --coverage --coverage-path=coverage/lcov.info --test-randomize-ordering-seed=random --concurrency=10

      - name: 📈 Upload Coverage
        uses: codecov/codecov-action@v4.5.0
        with:
          # not needed for public repos
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true